name: bot
version: 0.15.1-dev
author: Kevin Moore <kevin@thinkpixellab.com>
description: A collection of (mostly) general libraries to make working with Dart more productive.
homepage: https://github.com/kevmoo/bot.dart
documentation: http://kevmoo.github.com/bot.dart
environment:
  sdk: '>=0.4.2+2.r20138'
dependencies:
  unittest: '>=0.4.2'
  args: '>=0.4.2'
  logging: '>=0.4.2'
  pathos: '>=0.4.2'
  meta: '>=0.4.2'
dev_dependencies:
  html5lib: '>=0.4.1'
  browser: '>=0.4.2'
