name: bot
version: 0.22.1-dev
author: Kevin Moore <kevin@thinkpixellab.com>
description: A collection of (mostly) general libraries to make working with Dart more productive.
homepage: https://github.com/kevmoo/bot.dart
documentation: http://kevmoo.github.io/bot.dart
environment:
  sdk: '>=0.6.3+3'
dependencies:
  meta: '>=0.6.3'
  pathos: '>=0.6.3'
  unittest: '>=0.6.3'
dev_dependencies:
  browser: '>=0.6.3'
  hop: '>=0.22.2'
  html5lib: '>=0.4.3'
  serialization: '>=0.6.3'
