name: hop
author: Kevin Moore <kevin@thinkpixellab.com>
homepage: https://github.com/kevmoo/bot.dart
version: 0.3.0
description: A version of Make (or Ruby Rake or Coffeescript Cake or Javascript Jake) for Dart
dependencies:
  unittest:
    sdk: unittest
  args:
    sdk: args
  bot:
    git:
      url: https://github.com/kevmoo/bot.dart.git
      ref: master
