name: bot
version: 0.12.0-dev
author: Kevin Moore <kevin@thinkpixellab.com>
description: A collection of (mostly) general libraries to make working with Dart more productive.
homepage: https://github.com/kevmoo/bot.dart
environment:
  sdk: '>=0.3.4'
dependencies:
  unittest: '>=0.3.4'
  args: '>=0.3.4'
  logging: '>=0.3.4'
  meta: '>=0.3.4'
