name: bot
version: 0.15.0-dev
author: Kevin Moore <kevin@thinkpixellab.com>
description: A collection of (mostly) general libraries to make working with Dart more productive.
homepage: https://github.com/kevmoo/bot.dart
environment:
  sdk: '>=0.4.0+0.r18915'
dependencies:
  unittest: '>=0.4.0'
  html5lib: '>=0.3.3+2'
  args: '>=0.4.0'
  browser: '>=0.4.0'
  logging: '>=0.4.0'
  pathos: '>=0.4.0'
  meta: '>=0.4.0'
