name: bot
author: Kevin Moore <kevin@thinkpixellab.com>
homepage: https://github.com/kevmoo/bot.dart
version: 0.10.0
description: A collection of (mostly) general libraries to make working with Dart more productive.
dependencies:
  args: '>=0.2.10 <2.11.0'
  meta: '>=0.2.10 <2.11.0'
  logging: '>=0.2.10 <2.11.0'
  unittest: '>=0.2.10 <2.11.0'
