name: bot
author: Kevin Moore <kevin@thinkpixellab.com>
homepage: https://github.com/kevmoo/bot.dart
version: 0.0.1
description: A collection of (mostly) general libraries to make working with Dart more productive.
dependencies:
  unittest:
    sdk: unittest
