name: bot
author: Kevin Moore <kevin@thinkpixellab.com>
homepage: https://github.com/kevmoo/bot.dart
version: 0.6.0
description: A collection of (mostly) general libraries to make working with Dart more productive.
dependencies:
  unittest:
    sdk: unittest
  hop:
    git:
      url: https://github.com/kevmoo/hop.dart.git
      ref: master
