name: bot
author: Kevin Moore <kevin@thinkpixellab.com>
homepage: https://github.com/kevmoo/bot.dart
version: 0.9.0-beta2
description: A collection of (mostly) general libraries to make working with Dart more productive.
dependencies:
  args: '>=0.2.9 <2.10.0'
  meta: '>=0.2.9 <2.10.0'
  logging: '>=0.2.9 <2.10.0'
  unittest: '>=0.2.9 <2.10.0'
